# Generated by Django 6.0 on 2025-12-07 23:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0002_rename_end_date_election_election_end_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('VOTE_CAST', 'Vote Cast'), ('VOTER_ADDED', 'Voter Added'), ('CANDIDATE_APPROVED', 'Candidate Approved'), ('CANDIDATE_REJECTED', 'Candidate Rejected'), ('ELECTION_CREATED', 'Election Created'), ('POSITION_CREATED', 'Position Created'), ('OTP_REQUESTED', 'OTP Requested'), ('OTP_VERIFIED', 'OTP Verified')], max_length=50)),
                ('voter_reg_no', models.CharField(blank=True, max_length=100)),
                ('details', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('election', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='election.election')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
