# Generated by Django 6.0 on 2025-12-08 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_emailotp_email_alter_user_is_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
